// Code generated by mockery. DO NOT EDIT.

package merror

import mock "github.com/stretchr/testify/mock"

// mockTestError is an autogenerated mock type for the testError type
type mockTestError struct {
	mock.Mock
}

type mockTestError_Expecter struct {
	mock *mock.Mock
}

func (_m *mockTestError) EXPECT() *mockTestError_Expecter {
	return &mockTestError_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields:
func (_m *mockTestError) Error() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// mockTestError_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type mockTestError_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *mockTestError_Expecter) Error() *mockTestError_Error_Call {
	return &mockTestError_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *mockTestError_Error_Call) Run(run func()) *mockTestError_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockTestError_Error_Call) Return(_a0 string) *mockTestError_Error_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockTestError_Error_Call) RunAndReturn(run func() string) *mockTestError_Error_Call {
	_c.Call.Return(run)
	return _c
}

// newMockTestError creates a new instance of mockTestError. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTestError(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTestError {
	mock := &mockTestError{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
